const hostels = [
  {
    id: 1,
    name: 'Galaxy Hostel',
    price: '300,000',
    rating: 4.6,
    distance: '5 min walk',
    gender: 'Mixed',
    wifi: true,
    water: true,
    badge: 'Verified',
    badgeColor: 'bg-primary-50 text-primary-600',
    emoji: '🏠',
    bg: 'bg-green-50',
  },
  {
    id: 2,
    name: 'Victory Hostel',
    price: '280,000',
    rating: 4.5,
    distance: '8 min walk',
    gender: 'Mixed',
    wifi: true,
    water: false,
    badge: 'Top Rated',
    badgeColor: 'bg-blue-100 text-blue-700',
    emoji: '🏢',
    bg: 'bg-blue-50',
  },
  {
    id: 3,
    name: 'Tupendane Hostel',
    price: '250,000',
    rating: 4.3,
    distance: '10 min walk',
    gender: 'Mixed',
    wifi: false,
    water: true,
    badge: 'New',
    badgeColor: 'bg-amber-100 text-amber-700',
    emoji: '🏘️',
    bg: 'bg-amber-50',
  },
  {
    id: 4,
    name: 'William Hostel',
    price: '320,000',
    rating: 4.4,
    distance: '12 min walk',
    gender: 'Male',
    wifi: true,
    water: true,
    badge: 'Verified',
    badgeColor: 'bg-primary-50 text-primary-600',
    emoji: '🏡',
    bg: 'bg-purple-50',
  },
]